# Generated by Django 4.1.6 on 2023-04-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_cni", models.IntegerField(null=True)),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=30)),
                ("phone_number", models.CharField(max_length=20)),
            ],
        ),
    ]
