# Generated by Django 4.1.6 on 2023-04-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("desc", models.TextField()),
                ("image", models.ImageField(upload_to="img")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("upload_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
